### ISSUE TITLE
`Send` impls on `webm::mux` types are not sound

### ISSUE THREAD

**Issue by OxleyS** [DiamondLovesYou/rust-webm#14]
First, we establish that segment operations are in general not thread-safe. We can look at the [common method called by frame writers in libwebm](https://github.com/webmproject/libwebm/blob/75cff0674ecef25fb5457d6fdfa14ffeada19451/mkvmuxer/mkvmuxer.cc#L3494) and see:
- `CheckHeaderInfo()` may do a first-time-only header write
- The `tracks_` list is accessed unsynchronized
- Potential holding of audio frames in anticipation of video, also unsynchronized
- etc.

Meanwhile, the non-sys Rust wrapper impls `Send` for `Writer`, `Segment`, `AudioTrack`, and `VideoTrack`. This seems okay on the surface since we don't implement `Sync`, and `libwebm` does not use any thread-locals or anything. But nevertheless we can get ourselves into trouble:
```rust
let file = std::fs::File::create("/dev/null").unwrap();
let writer = webm::mux::Writer::new(file);
let mut segment = webm::mux::Segment::new(writer).unwrap();

let audio_track = segment.add_audio_track(48000, 1, None, webm::mux::AudioCodecId::Opus);
let other_audio_track = segment.add_audio_track(48000, 1, None, webm::mux::AudioCodecId::Opus);

// UB: Unsynchronized writes to the same segment
std::thread::spawn(move || {
  other_audio_track.add_frame(...);
});
audio_track.add_frame(...);
```

This particular example picks on segments and audio tracks, but in general any combination of the above four interfaces can be unsound, because there's no enforcement of the requirement that the writer and all its sub-objects move threads together. For that, I don't see a way around applying lifetime parameters to segments and tracks (although I understand the motivation to keep a simple public API).

**Comment by kornelski** [comment]
It's even worse than that:

```rust
        let writer = crate::mux::Writer::new(std::io::Cursor::new(Vec::new()));
        let mut segment = crate::mux::Segment::new(writer).unwrap();
        let mut audio_track = segment.add_audio_track(48000, 1, None, crate::mux::AudioCodecId::Opus);
        
        drop(segment);
        audio_track.add_frame(&[], 0, true); // crashes
```

Currently VideoTrack and AudioTrack just hold a bare raw pointer to the Segment. It needs to be `Arc<Mutex<Segment>>` instead (a lifetime would prevent UAF too, but it would be too cumbersome to use tracks tied to a temporary lifetime).

**Comment by OxleyS** [comment]
The `Arc<Mutex<Segment>>` approach is likely necessary under the current API for soundness, but it does come at a hefty cost. I do agree that adding lifetimes to `AudioTrack` and `VideoTrack` is probably too cumbersome.

If you don't mind an API break, an alternative approach might be to do something closer to what libwebm does, where creating a track just returns that track's number instead of a track object, and all writes happen through the segment:
```rust
// It's really just the ID (could be renamed as such). No lifetimes necessary
struct AudioTrack(u64); 

let writer = crate::mux::Writer::new(std::io::Cursor::new(Vec::new()));
let mut segment = crate::mux::Segment::new(writer).unwrap();

let audio_track = segment.add_audio_track(48000, 1, None, crate::mux::AudioCodecId::Opus);
segment.set_codec_private(audio_track, &[]);
segment.add_frame(audio_track, &[], 0, true);

drop(segment);
segment.add_frame(audio_track, &[], 0, true); // Compile error, use of moved value

some_other_segment.add_frame(audio_track, &[], 0, true); // Janky, but not undefined behavior
```

This is safe to impl `Send` on because the only persistent "live object" is the segment, making simple borrow checking on it sufficient to prevent both UAF and use on more than one thread at a time.

Of course, this means that your writers must have mutable access to the segment to do things with a track, but I think in most cases this will be true, especially considering my personal experience of players being very sensitive to inter-stream frame order. If the user really must write from multiple threads or highly separated locations, then they can wrap the segment in `Arc<Mutex>` themselves, for no more overhead than what we've proposed for the current API.

**Comment by kornelski** [comment]
Yes, explicit use of the segment fixes it nicely. 

I'll still release the existing solution for this semver range , because UAF is a serious issue. I have an idea to make it backwards compatible.

**Comment by OxleyS** [comment]
Apologies if this issue is not the best place to ask this - if you're not already working on it yourself, would you be okay with me taking a stab at implementing the API proposed [above](https://github.com/DiamondLovesYou/rust-webm/issues/14#issuecomment-2157015486)?
