### ISSUE TITLE
Feature request: Support `Writer` for `T` that is not `Seek`

### ISSUE THREAD

**Issue by OxleyS** [DiamondLovesYou/rust-webm#17]
In my particular use case of this library, we don't need the seeking headers or durations that are normally written on finalization, so we should be able to use a writer that doesn't support seeking.

This will require some changes on the `-sys` side to support passing `nullptr` for `get_position`/`set_position` seek-related functions, as well as an alternative constructor for `Writer`. If an API break is okay, then it may be best to remove `Writer::new()`, and have `Writer::from_seekable()` and `Writer::from_non_seekable()` instead. If we want to avoid an API break, I think it'd be acceptable to consider the seekable one "blessed" with `Writer::new()` and just add a `Writer::from_non_seekable()`.

I don't mind contributing these changes myself (once I'm ready to do so on my end), but I wanted to know what you guys thought about the API break. If we do plan to do it, we could probably lump it in the same major version bump as the change proposed in https://github.com/DiamondLovesYou/rust-webm/issues/14.

**Comment by kornelski** [comment]
Good idea. You can remove bounds from the `struct Writer` (they don't need to be on the struct), and add `fn new_non_seek()`.
